[tool.poetry]
name = "common"
version = "0.1.2"
description = ""
authors = ["Rubens"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
